1
SELECT ProductKey, COUNT(*)
FROM DimProduct
GROUP BY ProductKey
HAVING COUNT(*) > 1

SELECT COUNT(*)
FROM DimProduct
WHERE ProductKey IS NULL

2
SELECT SalesOrderNumber
, SalesOrderLineNumber
, COUNT(*)
FROM factresellersales
GROUP BY SalesOrderNumber, SalesOrderLineNumber
HAVING COUNT(*) > 1

SELECT COUNT(*)
FROM factresellersales
WHERE SalesOrderNumber IS NULL OR SalesOrderLineNumber IS NULL

3
SELECT COUNT(SALESORDERLINENUMBER)
, ORDERDATE
FROM factresellersales
WHERE ORDERDATE >='2020-01-01'
GROUP BY ORDERDATE

4
SELECT SUM(FS.SALESAMOUNT) AS TOTALQUANTITYSOLD 
, SUM(FS.ORDERQUANTITY) AS TOTALQUANTITYSOLD
, AVG(FS.UNITPRICE) AS AVARAGEUNITPRICE
, P.ENGLISHPRODUCTNAME AS PRODUCTNAME
FROM FACTRESELLERSALES FS
JOIN DIMPRODUCT P ON FS. PRODUCTKEY= P.PRODUCTKEY
WHERE ORDERDATE >= '2020-01-01'
GROUP BY PRODUCTNAME

5
SELECT SUM(FS.SALESAMOUNT) AS TOTALREVENUE
, SUM(FS.ORDERQUANTITY) TOTALQUANTITYSOLD
,P.PRODUCTKEY
FROM factresellersales FS
JOIN DIMPRODUCT P ON FS.ProducTKEY= P.PRODUCTKEY
GROUP BY P. PRODUCTKEY

6
SELECT G.CITY AS CITY
,SUM(FS.SALESAMOUNT) AS TOTALREVENUE
FROM FACTRESELLERSALES FS
JOIN dimgeography G ON FS.SALESTERRITORYKEY=G.SALESTERRITORYKEY
WHERE FS.ORDERDATE >= '2020-01-01'
GROUP BY G.CITY
HAVING SUM(FS.SALESAMOUNT)>60000