-- 1
SELECT 
    C.CUSTOMER_ID, 
    C.FIRST_NAME, 
    C.LAST_NAME
FROM 
    CUSTOMER C
WHERE 
    C.CUSTOMER_ID NOT IN (
        SELECT 
            R.CUSTOMER_ID
        FROM 
            RENTAL R
        WHERE 
            R.RENTAL_DATE BETWEEN '2006-01-01' AND '2006-01-31'
    );
-- 2 
SELECT 
    F.TITLE AS TitoloFilm,
    COUNT(R.RENTAL_ID) AS NumeroNoleggi
FROM 
    RENTAL R
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
WHERE 
    R.RENTAL_DATE BETWEEN '2005-10-01' AND '2005-12-31'
GROUP BY 
    F.TITLE
HAVING 
    COUNT(R.RENTAL_ID) > 10
ORDER BY 
    NumeroNoleggi DESC;

-- 3
SELECT 
    COUNT(R.RENTAL_ID) AS NumeroNoleggi
FROM 
    RENTAL R
WHERE 
    R.RENTAL_DATE = '2006-01-01';
   -- 4 
SELECT SUM(amount) AS SOMMAINCASSIWEEKEND
FROM PAYMENT P
JOIN RENTAL R ON P.RENTAL_ID = R.RENTAL_ID
WHERE dayofweek(rental_date) IN (7,1);
-- 5 
SELECT SUM(AMOUNT) AS INCASSO
,P.CUSTOMER_ID
FROM CUSTOMER C
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY P.CUSTOMER_ID 
LIMIT 1;
-- 6 
SELECT 
    F.TITLE AS TitoloFilm,
    AVG(DATEDIFF(R.RETURN_DATE, R.RENTAL_DATE)) AS DurataMediaNoleggio
FROM 
    RENTAL R
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
WHERE 
    R.RETURN_DATE IS NOT NULL 
GROUP BY 
    F.TITLE
ORDER BY 
    DurataMediaNoleggio DESC
LIMIT 5;

-- 7
WITH NoleggiConDifferenza AS (
    SELECT 
        R.CUSTOMER_ID,
        R.RENTAL_DATE,
        LEAD(R.RENTAL_DATE) OVER (PARTITION BY R.CUSTOMER_ID ORDER BY R.RENTAL_DATE) AS NextRentalDate
    FROM 
        RENTAL R
)
SELECT 
    CUSTOMER_ID,
    AVG(DATEDIFF(NextRentalDate, RENTAL_DATE)) AS TempoMedioTraNoleggi
FROM 
    NoleggiConDifferenza
WHERE 
    NextRentalDate IS NOT NULL  
GROUP BY 
    CUSTOMER_ID;

    -- 8
SELECT 
    MONTH(R.RENTAL_DATE) AS Mese,
    COUNT(R.RENTAL_ID) AS NumeroNoleggi
FROM 
    RENTAL R
WHERE 
    YEAR(R.RENTAL_DATE) = 2005
GROUP BY 
    MONTH(R.RENTAL_DATE)
ORDER BY 
    Mese;

-- 9
SELECT 
    F.TITLE AS TitoloFilm,
    R.RENTAL_DATE AS DataNoleggio,
    COUNT(R.RENTAL_ID) AS NumeroNoleggi
FROM 
    RENTAL R
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
GROUP BY 
    F.TITLE, R.RENTAL_DATE
HAVING 
    COUNT(R.RENTAL_ID) >= 2
ORDER BY 
    R.RENTAL_DATE, F.TITLE;

-- 10 
SELECT 
    AVG(DATEDIFF(R.RETURN_DATE, R.RENTAL_DATE)) AS TempoMedioNoleggio
FROM 
    RENTAL R
WHERE 
    R.RETURN_DATE IS NOT NULL;  
