

-- 2
 SELECT 
    COUNT(C.CUSTOMER_ID) AS NumeroClientiRegistrati, 
    YEAR(C.CREATE_DATE) AS AnnoRegistrazione
FROM 
    CUSTOMER C
JOIN 
    STORE S ON C.store_id = S.store_id
WHERE 
   YEAR(C.CREATE_DATE) = 2006
GROUP BY 
    YEAR(C.CREATE_DATE);

-- 3 
SELECT RENTAL_DATE AS DATA_NOLEGGIO
,COUNT(RENTAL_ID) AS CODICE_NOLEGGIO
FROM RENTAL 
 WHERE RENTAL_DATE = '2006-01-01' 
GROUP BY REntal_date;

-- 4
SELECT 
    F.TITLE AS TitoloFilm,
    COUNT(R.RENTAL_ID) AS NumeroNoleggi,
    R.RENTAL_DATE AS DataNoleggio,
    C.CUSTOMER_ID AS CodiceCliente,
    C.FIRST_NAME AS NomeCliente,
    C.LAST_NAME AS CognomeCliente
FROM 
    RENTAL R
JOIN 
    CUSTOMER C ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
WHERE 
    r.rental_date between '2005-05-28' and '2005-06-03'
GROUP BY 
    F.TITLE, R.RENTAL_DATE, C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY 
    R.RENTAL_DATE DESC;

-- 5
SELECT 
    CAT.NAME AS CategoriaFilm,
    AVG(DATEDIFF(R.RETURN_DATE, R.RENTAL_DATE)) AS DurataMediaNoleggio
FROM 
    RENTAL R
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
JOIN 
    FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
JOIN 
    CATEGORY CAT ON FC.CATEGORY_ID = CAT.CATEGORY_ID
WHERE 
    R.RETURN_DATE IS NOT NULL  
GROUP BY 
    CAT.NAME
ORDER BY 
    DurataMediaNoleggio DESC;

-- 6 
SELECT 
    R.RENTAL_DATE AS DataNoleggio,
    DATEDIFF(R.RETURN_DATE, R.RENTAL_DATE) AS DurataNoleggio
FROM 
    RENTAL R
WHERE 
    R.RETURN_DATE IS NOT NULL  
ORDER BY 
    DurataNoleggio DESC
LIMIT 1;


SELECT 
    F.TITLE AS TitoloFilm,
    -- COUNT(R.RENTAL_ID) AS NumeroNoleggi,
    R.RENTAL_DATE AS DataNoleggio,
    C.CUSTOMER_ID AS CodiceCliente,
    C.FIRST_NAME AS NomeCliente,
    C.LAST_NAME AS CognomeCliente
FROM 
    RENTAL R
JOIN 
    CUSTOMER C ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN 
    INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN 
    FILM F ON I.FILM_ID = F.FILM_ID
WHERE 
DATEDIFF('2005-06-03 23:00:00', R.RENTAL_DATE)<=6
and DATEDIFF('2005-06-03 23:00:00', R.RENTAL_DATE)>=0
GROUP BY 
F.TITLE, R.RENTAL_DATE, C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY 
    R.RENTAL_DATE DESC;